version: '3.8'
services: 
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'python manage.py runserver 0.0.0.0:8000'
        ports: 
            - 8000:8000
        volumes: 
            - .:/app
        depends_on: 
            - db

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'python consumer.py'
        depends_on:
            - db

    db:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: terror_watch_admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: p4ssw0rd
            MYSQL_ROOT_PASSWORD: p4ssw0rd
        volumes: 
            - .dbdata:/var/lib/mysql
        ports: 
            - 33066:3306
